blank_issues_enabled: false
contact_links:
  - name: SugarcaneMC Discord
    url: https://sugarcanemc.org/discord
    about: If you are having issues, come to our Discord server and we will try to help you out!
